# Generated by Django 6.0 on 2026-02-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifications.edition'),
        ),
        migrations.AddField(
            model_name='game',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifications.region'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('title', 'released_at', 'edition', 'region')},
        ),
    ]
