services:
  django:
    build:
      context: .
    container_name: gameshelf_backend
    restart: always
    env_file:
      - ./gameshelf-backend/.env

    user: "1000:1000"

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    expose:
      - 8000

    depends_on:
      - redis

    command: uv run gunicorn main.wsgi:application --bind 0.0.0.0:8000 --workers 3


  rqworker:
    build:
      context: .
    container_name: gameshelf_rqworker
    restart: always

    env_file:
      - ./gameshelf-backend/.env

    user: "1000:1000"

    depends_on:
      - redis

    command: uv run python manage.py rqworker default


  redis:
    image: redis:7-alpine
    container_name: gameshelf_redis
    restart: always
    volumes:
      - redis_data:/data


  nginx:
    image: nginx:stable-alpine
    container_name: gameshelf_nginx
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    depends_on:
      - django


  init:
    build:
      context: .
    container_name: gameshelf_init

    env_file:
      - ./gameshelf-backend/.env

    user: "1000:1000"

    depends_on:
      - redis

    command: sh -c "just makemigrations && just migrate && just seed && just create-su"


volumes:
  static_volume:
  media_volume:
  redis_data:
