# Generated by Django 6.0 on 2026-02-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='description',
        ),
    ]
