# Generated by Django 6.0 on 2026-04-21 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='classifications_developer_unique_active_slug'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='classifications_developer_unique_active_name')],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=160)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='classifications_edition_unique_active_slug'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='classifications_edition_unique_active_name')],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('acronym', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='classifications_genre_unique_active_slug'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='classifications_genre_unique_active_name')],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='classifications_platform_unique_active_slug'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='classifications_platform_unique_active_name')],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='classifications_publisher_unique_active_slug'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='classifications_publisher_unique_active_name')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('acronym', models.CharField(max_length=2)),
                ('igdb_id', models.IntegerField(unique=True)),
                ('rating_organization', models.CharField(blank=True, choices=[('PEGI', 'PEGI'), ('ESRB', 'ESRB'), ('CERO', 'CERO'), ('USK', 'USK'), ('GRAC', 'GRAC'), ('CLASS_IND', 'CLASS_IND'), ('ACB', 'ACB'), ('IARC', 'IARC')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='classifications_region_unique_active_slug'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='classifications_region_unique_active_name')],
            },
        ),
        migrations.CreateModel(
            name='PlatformSlugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_aliases', to='classifications.platform')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='classifications_platformslugalias_unique_active_slug')],
            },
        ),
    ]
