# Generated by Django 6.0 on 2026-02-09 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='region',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='region',
        ),
    ]
