export const PLATFORM_MAP: Record<string, string> = {
    'super-famicom': 'mdi:gamepad-square',
    'nintendo-switch': 'simple-icons:nintendoswitch',
    'android': 'simple-icons:android',
    'mobile': 'mdi:cellphone',                          // Legacy Mobile Device
    'linux': 'simple-icons:linux',
    'pc-dos': 'mdi:monitor-old',                        // DOS / PC DOS
    'dos': 'mdi:monitor-old',
    'win': 'mdi:microsoft-windows',                     // alias
    'pc-microsoft-windows': 'mdi:microsoft-windows',
    'playstation-3': 'simple-icons:playstation3',
    'playstation': 'simple-icons:playstation',
    'playstation-portable': 'simple-icons:playstationportable',
    'steamvr': 'mdi:virtual-reality',
    'wii-u': 'mdi:nintendo-wiiu',
    'nintendo-ds': 'simple-icons:nintendo3ds',
    'e-reader-slash-card-e-reader': 'mdi:alpha-e-box',
    'web-browser': 'mdi:web',
    'browser': 'mdi:web',
    'commodore-c64128max': 'simple-icons:commodore',
    'c64': 'simple-icons:commodore',
    'playstation-4': 'simple-icons:playstation4',
    'playstation-vita': 'simple-icons:playstationvita',
    'ios': 'simple-icons:ios',
    'mac': 'simple-icons:macos',
    'nintendo-entertainment-system--nes': 'mdi:nintendo-game-boy',
    'nes': 'mdi:nintendo-game-boy',
    'xbox-one': 'mdi:microsoft-xbox',
    'playstation-5': 'simple-icons:playstation5',
    '3do-interactive-multiplayer': 'mdi:rotate-3d',
    '3do': 'mdi:rotate-3d',
    'nintendo-3ds': 'simple-icons:nintendo3ds',
    'arcade': 'mdi:gamepad-variant',
    'wii': 'mdi:wii',
    'sega-mega-drivegenesis': 'simple-icons:sega',
    'amiga': 'mdi:chip',
    'xbox': 'simple-icons:xbox',
    'playstation-2': 'simple-icons:playstation2',

    // --- Nintendo ---
    'n64': 'mdi:gamepad-variant',                       // Nintendo 64
    'nintendo-64': 'mdi:gamepad-variant',
    'ngc': 'mdi:nintendo-game-boy',                     // GameCube
    'nintendo-gamecube': 'mdi:nintendo-game-boy',
    'gb': 'mdi:nintendo-game-boy',                      // Game Boy
    'gba': 'mdi:nintendo-game-boy',                     // Game Boy Advance
    'gbc': 'mdi:nintendo-game-boy',                     // Game Boy Color
    'dsi': 'simple-icons:nintendo3ds',                           // Nintendo DSi
    'new-nintendo-3ds': 'simple-icons:nintendo3ds', 
    'virtual-console--nintendo': 'mdi:gamepad-variant',
    'nintendo-eshop': 'mdi:nintendo-switch',
    'wonderswan': 'mdi:gamepad-variant',
    'wonderswan-color': 'mdi:gamepad-variant',
    'swancrystal': 'mdi:gamepad-variant',
    'pokemon-mini': 'mdi:gamepad-square',
    'n-gage': 'mdi:cellphone',
    'wiiware': 'mdi:wii',
    'family-computer-disk-system': 'mdi:floppy',
    'fds': 'mdi:floppy',
    'famicom': 'mdi:nintendo-game-boy',
    'snes': 'mdi:gamepad-square',
    'super-nintendo-entertainment-system--snes': 'mdi:gamepad-square',
    'nintendo-switch-2': 'simple-icons:nintendoswitch',

    // --- PlayStation ---
    'ps-network': 'simple-icons:playstation',
    'ps-vr': 'mdi:virtual-reality',
    'playstation-vr': 'mdi:virtual-reality',

    // --- Xbox ---
    'xbox-360': 'simple-icons:xbox',
    'xbox-series-xs': 'simple-icons:xbox',
    'xbox-live-arcade': 'mdi:microsoft-xbox',

    // --- Sega ---
    'sega-master-system': 'simple-icons:sega',
    'sega-saturn': 'simple-icons:sega',
    'sega-32x': 'simple-icons:sega',
    'sega-cd': 'simple-icons:sega',
    'sega-game-gear': 'simple-icons:sega',
    'dc': 'simple-icons:sega',                          // Dreamcast
    'dreamcast': 'simple-icons:sega',
    'sg-1000': 'simple-icons:sega',

    // --- Atari ---
    'atari2600': 'mdi:atari',
    'atari-2600': 'mdi:atari',
    'atari7800': 'mdi:atari',
    'atari-7800': 'mdi:atari',
    'atari5200': 'mdi:atari',
    'atari-5200': 'mdi:atari',
    'lynx': 'mdi:atari',                                // Atari Lynx
    'atari-lynx': 'mdi:atari',
    'jaguar': 'mdi:atari',                              // Atari Jaguar
    'atari-jaguar': 'mdi:atari',
    'atari-jaguar-cd': 'mdi:atari',
    'atari-st': 'mdi:atari',
    'atari8bit': 'mdi:atari',
    'atari-8-bit': 'mdi:atari',

    // --- PC / Computer platforms ---
    'steamos': 'simple-icons:steam',
    'steam': 'simple-icons:steam',
    'onlive-game-system': 'mdi:cloud-outline',
    'stadia': 'simple-icons:googlestadia',
    'google-stadia': 'simple-icons:googlestadia',
    'windows-mixed-reality': 'mdi:virtual-reality',
    'oculus-vr': 'mdi:virtual-reality',
    'gear-vr': 'mdi:virtual-reality',
    'daydream': 'mdi:virtual-reality',
    'amazon-fire-tv': 'simple-icons:amazon',
    'amazon-fire-tv-stick': 'simple-icons:amazon',
    'blackberry': 'mdi:cellphone',
    'windows-phone': 'mdi:microsoft-windows',
    'apple-ii': 'simple-icons:apple',
    'appleii': 'simple-icons:apple',
    'apple-iigs': 'simple-icons:apple',
    'apple-pippin': 'simple-icons:apple',

    // --- Commodore ---
    'c16': 'simple-icons:commodore',
    'c-plus-4': 'simple-icons:commodore',
    'vic-20': 'simple-icons:commodore',
    'commodore-cdtv': 'simple-icons:commodore',
    'amiga-cd32': 'simple-icons:commodore',
    'cpet': 'simple-icons:commodore',

    // --- NEC / PC-Engine ---
    'turbografx-16-slash-pc-engine': 'mdi:gamepad-variant',
    'turbografx-16-slash-pc-engine-cd': 'mdi:gamepad-variant',
    'pc-engine-supergrafx': 'mdi:gamepad-variant',

    // --- SNK / Neo Geo ---
    'neogeocd': 'mdi:gamepad-square',
    'neo-geo-cd': 'mdi:gamepad-square',
    'neo-geo-mvs': 'mdi:gamepad-square',
    'neo-geo-aes': 'mdi:gamepad-square',
    'neo-geo-pocket': 'mdi:gamepad-square',
    'neo-geo-pocket-color': 'mdi:gamepad-square',
    'hyper-neo-geo-64': 'mdi:gamepad-square',

    // --- VR ---
    'playstation-vr2': 'mdi:virtual-reality',
    'meta-quest-2': 'simple-icons:meta',
    'meta-quest-3': 'simple-icons:meta',

    // --- Obscure / retro computers ---
    'zx-spectrum': 'mdi:chip',
    'msx': 'mdi:chip',
    'msx2': 'mdi:chip',
    'sharp-x68000': 'mdi:chip',
    'sharp-x1': 'mdi:chip',
    'fm-7': 'mdi:chip',
    'fm-towns': 'mdi:chip',
    'pc-88': 'mdi:chip',
    'pc-98': 'mdi:chip',
    'pc-8801': 'mdi:chip',
    'acpc': 'mdi:chip',                                 // Amstrad CPC
    'amstrad-pcw': 'mdi:chip',
    'amstrad-gx4000': 'mdi:chip',
    'acorn-archimedes': 'mdi:chip',
    'acorn-electron': 'mdi:chip',
    'bbcmicro': 'mdi:chip',
    'trs-80': 'mdi:chip',
    'trs-80-color-computer': 'mdi:chip',
    'dragon-32-slash-64': 'mdi:chip',
    'tatung-einstein': 'mdi:chip',
    'thomson-mo5': 'mdi:chip',
    'nec-pc-6000-series': 'mdi:chip',
    'texas-instruments-ti-99': 'mdi:chip',
    'vectrex': 'mdi:gamepad-square',
    'virtual-boy': 'mdi:virtual-reality',
    'nuon': 'mdi:disc-player',
    'philips-cd-i': 'mdi:disc-player',
    'philips-videopac-g7000': 'mdi:gamepad-variant',
    'intellivision': 'mdi:gamepad-variant',
    'colecovision': 'mdi:gamepad-variant',
    'astrocade': 'mdi:gamepad-variant',
    'fairchild-channel-f': 'mdi:gamepad-variant',
    'magnavox-odyssey': 'mdi:gamepad-variant',
    'odyssey--1': 'mdi:gamepad-variant',
    'microvision': 'mdi:gamepad-variant',
    'tapwave-zodiac': 'mdi:cellphone',
    'ouya': 'mdi:gamepad-variant',
    'evercade': 'mdi:gamepad-variant',
    'playdate': 'mdi:gamepad-variant',

    // --- Streaming / Cloud ---
    'xbox-cloud-gaming': 'simple-icons:xbox',
    'nvidia-shield': 'simple-icons:nvidia',

    // --- Misc / unknown hardware ---
    'analog-electronics': 'mdi:cpu-32-bit',
    'analogueelectronics': 'mdi:cpu-32-bit',
    'microcomputer': 'mdi:chip',
    'legacy-computer': 'mdi:monitor-old',
    'pdp-1': 'mdi:chip',
    'pdp-7': 'mdi:chip',
    'pdp-8': 'mdi:chip',
    'pdp-10': 'mdi:chip',
    'pdp-11': 'mdi:chip',
    'hp2100': 'mdi:chip',
    'hp3000': 'mdi:chip',
    'edsac--1': 'mdi:chip',
    'nimrod': 'mdi:chip',
    'imlac-pds1': 'mdi:chip',
    'gt40': 'mdi:chip',
    'cdccyber70': 'mdi:chip',
    'plato': 'mdi:chip',
    'call-a-computer': 'mdi:chip',
    'sds-sigma-7': 'mdi:chip',
    'donner30': 'mdi:chip',

    // --- AY chips (IGDB has these as platforms) ---
    'ay-3-8500': 'mdi:chip',
    'ay-3-8603': 'mdi:chip',
    'ay-3-8605': 'mdi:chip',
    'ay-3-8606': 'mdi:chip',
    'ay-3-8607': 'mdi:chip',
    'ay-3-8610': 'mdi:chip',
    'ay-3-8710': 'mdi:chip',
    'ay-3-8760': 'mdi:chip',
    'vc-4000': 'mdi:chip',
    '1292-advanced-programmable-video-system': 'mdi:chip',
};